SQL> select ename from emp where hiredate < (select max(hiredate) from emp);

ENAME
----------
SMITH
ALLEN
WARD
JONES
MARTIN
BLAKE
CLARK
SCOTT
KING
TURNER
JAMES
FORD
MILLER

13 rows selected.

SQL> SELECT ENAME FROM EMP WHERE JOB!='MANAGER' AND SAL > 
  2  (select min(sal) from emp where job='MANAGER');

ENAME
----------
SCOTT
KING
FORD

SQL> SELECT ENAME FROM EMP WHERE HIREDATE > (SELECT ADD_MONTHS(MIN(HIREDATE),48) FROM EMP) AND 
  2  SAL<(SELECT SAL FROM EMP WHERE ENAME='BLAKE');

ENAME
----------
ADAMS

SQL> SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES') AND COMM>0 
  2  AND HIREDATE<(SELECT MAX(HIREDATE) FROM EMP);

     EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     DEPTNO
---------- ---------- --------- ---------- --------- ---------- ---------- ----------
      7499 ALLEN      SALESMAN        7698 20-FEB-81       1600        300         30
      7521 WARD       SALESMAN        7698 22-FEB-81       1250        500         30
      7654 MARTIN     SALESMAN        7698 28-SEP-81       1250       1400         30

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE EMPNO = 
  2  (SELECT MGR FROM EMP WHERE EMPNO=
  3  (SELECT MGR FROM EMP WHERE ENAME ='WARD')));

DNAME
--------------
ACCOUNTING

SQL> SELECT DNAME FROM DEPT WHERE DEPTNO IN 
  2  (SELECT DEPTNO FROM EMP WHERE SAL >
  3  (SELECT AVG(SAL) FROM EMP));

DNAME
--------------
SALES
RESEARCH
ACCOUNTING

SQL> SELECT ENAME FROM EMP WHERE SAL = 
  2  (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 
  3  (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH'));

ENAME
----------
SMITH
